# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Milhouse < Formula
  desc "Autonomous PRD-driven development CLI powered by Claude"
  homepage "https://github.com/daydemir/milhouse"
  version "0.4.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daydemir/milhouse/releases/download/v0.4.5/milhouse_0.4.5_darwin_amd64.tar.gz"
      sha256 "20f43494be239bc4c7a86fefcb61f0298b7af207ff6d6a9fb1940c22b2cab5d2"

      def install
        bin.install "mil"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daydemir/milhouse/releases/download/v0.4.5/milhouse_0.4.5_darwin_arm64.tar.gz"
      sha256 "d6c1af188b238d2db7d9b87ab1ec989f23ca89fe1c834a1c401496393a48bf04"

      def install
        bin.install "mil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daydemir/milhouse/releases/download/v0.4.5/milhouse_0.4.5_linux_amd64.tar.gz"
      sha256 "f650bfb839c599a76b8c481410e730bc8fd678f6c1b01856c9cb3e34167a3d89"
      def install
        bin.install "mil"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daydemir/milhouse/releases/download/v0.4.5/milhouse_0.4.5_linux_arm64.tar.gz"
      sha256 "1c4fc6ee68ce7c118810b5d0c47f043e0bb5dc12306f6b17cbe8ec1ef29970e6"
      def install
        bin.install "mil"
      end
    end
  end

  test do
    system "#{bin}/mil", "version"
  end
end
