# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Milhouse < Formula
  desc "Autonomous PRD-driven development CLI powered by Claude"
  homepage "https://github.com/daydemir/milhouse"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daydemir/milhouse/releases/download/v0.4.3/milhouse_0.4.3_darwin_amd64.tar.gz"
      sha256 "02deecde099d02ab123521e456e20c7f3ca5102acd2252baf02236a21f7c339d"

      def install
        bin.install "mil"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daydemir/milhouse/releases/download/v0.4.3/milhouse_0.4.3_darwin_arm64.tar.gz"
      sha256 "3d8a34bc3d2787bca7fba3e202920c94dd4028ceba3fa80227030f802ec0d7c3"

      def install
        bin.install "mil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daydemir/milhouse/releases/download/v0.4.3/milhouse_0.4.3_linux_amd64.tar.gz"
      sha256 "98500463f4ec58bfe0ddefe61fbb75368ff746654cb60fefb51f7d0ddc259e2a"
      def install
        bin.install "mil"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daydemir/milhouse/releases/download/v0.4.3/milhouse_0.4.3_linux_arm64.tar.gz"
      sha256 "6d8ea56e5e076bc87449f56251399a8be2c9e990f8469db36ab42ed3e6c794b5"
      def install
        bin.install "mil"
      end
    end
  end

  test do
    system "#{bin}/mil", "version"
  end
end
