# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Millhouse < Formula
  desc "Autonomous PRD-driven development CLI powered by Claude"
  homepage "https://github.com/suelio/millhouse"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daydemir/millhouse/releases/download/v0.3.1/millhouse_0.3.1_darwin_amd64.tar.gz"
      sha256 "773945c99e656ab7f9ab88c157841c3ecf5cd8a3cf1a1d2f7e9862ae3c5ffbe1"

      def install
        bin.install "mil"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daydemir/millhouse/releases/download/v0.3.1/millhouse_0.3.1_darwin_arm64.tar.gz"
      sha256 "c7936c1bb4d55e73ab1beb404175317fc9b0bc3481eea43bb5a9c91250d7921f"

      def install
        bin.install "mil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daydemir/millhouse/releases/download/v0.3.1/millhouse_0.3.1_linux_amd64.tar.gz"
      sha256 "c4cf3f6f58f32f70ae5402c0cb7260662f90c817b15e87739b18ea9d1f53e789"
      def install
        bin.install "mil"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daydemir/millhouse/releases/download/v0.3.1/millhouse_0.3.1_linux_arm64.tar.gz"
      sha256 "32f5f0208848bba3a834abff7309dc64f91f5cc3af68583e2655805e5f78faf3"
      def install
        bin.install "mil"
      end
    end
  end

  test do
    system "#{bin}/mil", "version"
  end
end
