# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ralph < Formula
  desc "Autonomous plan execution engine built on GSD planning"
  homepage "https://github.com/daydemir/ralph"
  version "0.9.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daydemir/ralph/releases/download/v0.9.3/ralph_0.9.3_darwin_amd64.tar.gz"
      sha256 "6a3891b6e6dc54bcf9f723f5eae42bd9c50acb179f4225f37476731560ebbadb"

      def install
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daydemir/ralph/releases/download/v0.9.3/ralph_0.9.3_darwin_arm64.tar.gz"
      sha256 "6b36ddb8024fdd70cd84fb58c97f0b5b1404563de21d2a153c88ced48516f3a9"

      def install
        bin.install "ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daydemir/ralph/releases/download/v0.9.3/ralph_0.9.3_linux_amd64.tar.gz"
      sha256 "d9a9a95372bacc61a149e21c12cedde05435bace5dc7e52bec7342cb8272d767"
      def install
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daydemir/ralph/releases/download/v0.9.3/ralph_0.9.3_linux_arm64.tar.gz"
      sha256 "b6da14b935d67e920ba46508be239d2210faf21a4534fa81532cf21c4d16b655"
      def install
        bin.install "ralph"
      end
    end
  end

  test do
    system "#{bin}/ralph", "--version"
  end
end
