# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ralph < Formula
  desc "Autonomous plan execution engine built on GSD planning"
  homepage "https://github.com/daydemir/ralph"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daydemir/ralph/releases/download/v0.2.1/ralph_0.2.1_darwin_amd64.tar.gz"
      sha256 "c8ef9df33724861a2c73457689a39aa64511bd2d22d5ecbd2dc3e3476f0c4ba5"

      def install
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daydemir/ralph/releases/download/v0.2.1/ralph_0.2.1_darwin_arm64.tar.gz"
      sha256 "d0d7af6bf571a3633cc6b5845f4d7d011c1c62b472ef1d456cedd34565a0a9ea"

      def install
        bin.install "ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daydemir/ralph/releases/download/v0.2.1/ralph_0.2.1_linux_amd64.tar.gz"
      sha256 "c19176f445812624240680bc97e6ee10d251caaf38d95abed6c9433cdd433511"
      def install
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daydemir/ralph/releases/download/v0.2.1/ralph_0.2.1_linux_arm64.tar.gz"
      sha256 "502e03e589de58459c7892fea0401c6a2d9395f0b696a23228f8a2a04fd548b2"
      def install
        bin.install "ralph"
      end
    end
  end

  test do
    system "#{bin}/ralph", "--version"
  end
end
